version: "3.3"
services: 
  web:
    build: .
    ports:
      - 8004:8004
  db:
    image: mysql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boxbilling
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080