version: "3.9"
services: 
  web:
    build: .
    ports:
      - 8004:8004
    environment: 
      DB_HOST: database
      DB_NAME: boxbilling
      DB_USER: root
      DB_PASS: root
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root