version: "3.3"
services: 
  web:
    build: .
    ports:
      - 8004:8004
    environment: 
      DB_HOST: database
      DB_NAME: boxbilling
      DB_USER: root
      DB_PASS: root
    restart: always
  database:
    image: mysql:alpine
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: billing
      - MYSQL_USER: root
      - MYSQL_PASSWORD: root
    restart: always
  adminer:
    image: adminer:alpine
    restart: always
    ports:
      - 8080:8080